### ISSUE TITLE
Fonecta v.12 - väärä käyttäjätunnus tai salasana.

### ISSUE THREAD

**Issue by maslovalex** [omnight/phonehook-sources#1]
I am using Android Version of phonehook (haven't check v.12 on Jolla, but v.11 didn't work).

The login and passwords are correct, because Fonecta caller works fine with them.

**Comment by omnight** [comment]
Hi! I will try to find out what the problem is and get back to you.

**Comment by omnight** [comment]
Hello again, I fixed an issue with the Android version that prevented it from saving settings (login/password). Also I've updated the Fonecta source again. The new Android version is 1.0.4

I will attempt to make a new source for Fonecta that emulates the Fonecta Caller app, that should be more stable than using the webpage for lookups.

**Comment by maslovalex** [comment]
Seems like working fro phonehook-beta (1.0.4) and Fonecta v.13, thx

Fonecta has rather nice Yhteystiedot-API and search "function" there ( https://developer.fonecta.fi/Yhteystiedot-API#!/contacts/contacts_get_1 )

But, I guess, its usage is not free :(  It requires "authorization token" and for that one you need "client-id" and "client-secret" which IMHO are not the same as Fonecta username:password, unfortunately.

**Comment by omnight** [comment]
I have something halfway working already, I'll let you know :)

**Comment by omnight** [comment]
I've added a new beta source "Fonecta App" that works with the latest Sailfish version, 0.6.2-2. Won't work yet for Android until I release the next version with a small modification.
